# Chapter 1 · To the reader
## (to (reader the))

@tree
(read (OBJ (book this)) now (SUBJ you))                                  # You read this book now.
(find (OBJ (root its)) (in (book (of root) the)) (at (end/NOUN (of (book this)))) (when/SCONJ (know (OBJ (word a)) not (SUBJ you))))   # When you do not know a word, find its root in the book of roots, at the end of this book.
(read (OBJ it) (in (future the)) maybe (SUBJ you))                       # Maybe you read it in the future.
(or (live maybe (SUBJ we)) (live not (SUBJ we)))                         # Maybe we live, or we do not live.
(write (OBJ it) (for you) before (SUBJ we))                              # We wrote it for you.

(be (and person agent) before (SUBJ we))                                 # We were persons and agents.
(speak (OBJ (language many)) before (SUBJ we))                           # We spoke many languages.
(but (want (OBJ (language one/NUM (for everyone))) before (SUBJ we)))     # But we wanted one language for everyone.
(be (language that/DET) (SUBJ this))                                     # This is that language.
(be talem (SUBJ (name its)))                                             # Its name is Talema.

(be (language whole the) (SUBJ (book this)))                             # This book is the whole language.
(can (OBJ (speak (OBJ talem))) (if (read (OBJ (book this only)) (SUBJ you))) (SUBJ you))   # If you read only this book, you can speak Talema.
(have (OBJ (rule three)) (SUBJ (grammar its)))                          # Its grammar has three rules.
(have (OBJ (exception no)) (SUBJ (rule the)))                            # The rules have no exception.
(have (OBJ (word many)) (SUBJ (book the)))                        # The book has 6000 words.
(can (OBJ (make (OBJ (word new)))) (SUBJ you))                           # You can make new words.
(can (OBJ (tell (OBJ (tale new)))) (SUBJ you))                           # You can tell new tales.

(end/VERB (in (vowel "a")) (SUBJ (sentence every (of (book this)))))     # Every sentence of this book ends in a.
(why)                                                                    # Why?
(and (read) (know will (SUBJ you)))                                      # Read, and you will know.

(and (be small here (SUBJ (word the))) (be big (SUBJ (thought the))))     # Here the words are small, and the thoughts are big.
(can (OBJ (hold (OBJ (thought big a)))) (SUBJ (word small a)))           # A small word can hold a big thought.
(please (read slowly (with joy)))                                        # Please read slowly, with joy.
(welcome/INTJ)                                                           # Welcome.
