# Volume title page · The book of physics. A companion to Buke de lore fira.
## (book (of physics))

(be (book (of physics)) (SUBJ this))                                         # This is the book of physics.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of physics))) (SUBJ (book this)))                          # This book has the words of physics.
(read (OBJ (book (of mathematics))) too)                                     # Read the book of mathematics too.
