# Volume title page · The book of philosophy. A companion to Buke de lore fira.
## (book (of philosophy))

(be (book (of philosophy)) (SUBJ this))                                      # This is the book of philosophy.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of philosophy))) (SUBJ (book this)))                       # This book has the words of philosophy.
(read (OBJ (book (of logic))) too)                                           # Read the book of logic too.
