# Volume title page · The book of mathematics. A companion to Buke de lore fira.
## (book (of mathematics))

(be (book (of mathematics)) (SUBJ this))                                     # This is the book of mathematics.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of mathematics))) (SUBJ (book this)))                      # This book has the words of mathematics.
