# Volume title page · The book of food. A companion to Buke de lore fira.
## (book (of food))

(be (book (of food)) (SUBJ this))                                            # This is the book of food.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of (and food drink/NOUN)))) (SUBJ (book this)))            # This book has the words of food and drink.
