# Volume title page · The book of logic. A companion to Buke de lore fira.
## (book (of logic))

(be (book (of logic)) (SUBJ this))                                           # This is the book of logic.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of logic))) (SUBJ (book this)))                            # This book has the words of logic.
