# Volume title page · The book of conversation. A companion to Buke de lore fira.
## (book (of conversation))

(be (book (of conversation)) (SUBJ this))                                    # This is the book of conversation.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (play/NOUN a)) (SUBJ (book this)))                                # This book has a play.
(talk/VERB (in it) (SUBJ (people many)))                                     # In it, many people talk.
