# Volume title page · The book of morality. A companion to Buke de lore fira.
## (book (of morality))

(be (book (of morality)) (SUBJ this))                                        # This is the book of morality.
(read (OBJ (book (of (word first/ADJ)) the)) first/ADV)                      # Read the Book of the First Word first:
(have (OBJ (and (grammar the) (word first/ADJ the))) (SUBJ it))              # it has the grammar and the first words.
(have (OBJ (word (of morality))) (SUBJ (book this)))                         # This book has the words of morality.
(read (OBJ (book (of philosophy))) too)                                      # Read the book of philosophy too.
