<?xml version="1.0" encoding="UTF-8"?>
<lexicon version="1.0" xmlns="http://www.w3.org/2005/01/pronunciation-lexicon" alphabet="ipa" xml:lang="it-IT">
  <!-- Talema pronunciations, generated by scripts/conlang/speech.py; do not edit by hand -->
  <lexeme><grapheme>doge</grapheme><alias>doghe</alias></lexeme>
  <lexeme><grapheme>kige</grapheme><alias>kighe</alias></lexeme>
  <lexeme><grapheme>ge</grapheme><alias>ghe</alias></lexeme>
  <lexeme><grapheme>tonage</grapheme><alias>tonaghe</alias></lexeme>
  <lexeme><grapheme>rage</grapheme><alias>raghe</alias></lexeme>
  <lexeme><grapheme>kigi</grapheme><alias>kighi</alias></lexeme>
  <lexeme><grapheme>nage</grapheme><alias>naghe</alias></lexeme>
  <lexeme><grapheme>genete</grapheme><alias>ghenete</alias></lexeme>
  <lexeme><grapheme>ginona</grapheme><alias>ghinona</alias></lexeme>
  <lexeme><grapheme>gega</grapheme><alias>ghega</alias></lexeme>
  <lexeme><grapheme>gage</grapheme><alias>gaghe</alias></lexeme>
  <lexeme><grapheme>gagi</grapheme><alias>gaghi</alias></lexeme>
  <lexeme><grapheme>geneti</grapheme><alias>gheneti</alias></lexeme>
  <lexeme><grapheme>vege</grapheme><alias>veghe</alias></lexeme>
  <lexeme><grapheme>soge</grapheme><alias>soghe</alias></lexeme>
  <lexeme><grapheme>gehe</grapheme><alias>ghehe</alias></lexeme>
  <lexeme><grapheme>gini</grapheme><alias>ghini</alias></lexeme>
  <lexeme><grapheme>geva</grapheme><alias>gheva</alias></lexeme>
  <lexeme><grapheme>sinage</grapheme><alias>sinaghe</alias></lexeme>
  <lexeme><grapheme>kagi</grapheme><alias>kaghi</alias></lexeme>
  <lexeme><grapheme>geneta</grapheme><alias>gheneta</alias></lexeme>
  <lexeme><grapheme>dege</grapheme><alias>deghe</alias></lexeme>
  <lexeme><grapheme>page</grapheme><alias>paghe</alias></lexeme>
</lexicon>
